version: '3.7'

services:
  app_dev:
    build:
      context: .
    container_name: api-dev
    ports:
    - "3333:3333"
    volumes:
      - .:/usr/dev
    depends_on:
      - database
  database:
    container_name: api-database
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: api
      MYSQL_USER: docker
  

volumes:
  mysql:
    driver: local
    
       